# Generated by Django 3.1.5 on 2021-01-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210119_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Not paid'), ('3', 'Paid'), ('4', 'Completed'), ('5', 'Archival')], default='1', max_length=10),
        ),
    ]
